def towns():
    return [
        ('canberra', 'act'), 
        ('albury', 'nsw'),
        ('bathurst', 'nsw'),
        ('bowral', 'nsw'),
        ('gosford', 'nsw'),
        ('coffs harbour', 'nsw'),
        ('dubbo', 'nsw'),
        ('lismore', 'nsw'),
        ('nelson bay', 'nsw'),
        ('newcastle', 'nsw'),
        ('nowra', 'nsw'),
        ('orange', 'nsw'),
        ('port macquarie', 'nsw'),
        ('sydney', 'nsw'),
        ('tamworth', 'nsw'),
        ('wagga wagga', 'nsw'),
        ('wollongong', 'nsw'),
        ('darwin', 'nt'),
        ('brisbane', 'qld'),
        ('bundaberg', 'qld'),
        ('cairns', 'qld'),
        ('gladstone', 'qld'),
        ('hervey bay', 'qld'),
        ('mackay', 'qld'),
        ('rockhampton', 'qld'),
        ('maroochydore', 'qld'),
        ('surfers paradise', 'qld'),
        ('toowoomba', 'qld'),
        ('townsville', 'qld'),
        ('adelaide', 'sa'),
        ('berri', 'sa'),
        ('mount gambier', 'sa'),
        ('devonport', 'tas'),
        ('hobart', 'tas'),
        ('launceston', 'tas'),
        ('ballarat', 'vic'),
        ('bendigo', 'vic'),
        ('geelong', 'vic'),
        ('melbourne', 'vic'),
        ('melton', 'vic'),
        ('mildura', 'vic'),
        ('shepparton', 'vic'),
        ('traralgon', 'vic'),
        ('warragul', 'vic'),
        ('warrnambool', 'vic'),
        ('albany', 'wa'),
        ('bunbury', 'wa'),
        ('busselton', 'wa'),
        ('geraldton', 'wa'),
        ('kalgoorlie', 'wa'),
        ('perth', 'wa')
    ]
