name: Python application

on:
  push:
    paths-ignore:
      - "**"
    branches:
      - master
  # schedule:
  #   - cron:  '0 0 * * *'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tutorial_pull_realtime_data/Step_5_Requirements.txt
    - name: Run tutorial_pull_realtime_data/Step_5.py
      env:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
      run: |
        python tutorial_pull_realtime_data/Step_5.py.py
